env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    ALLOW_MISSING_DEPENDENCIES: "true"

    TLGTK: "ENCRYPTED[947923cb386537b5b64febb681804ae917eccc691323b69833f38c93107ee7b5be07e91449ddc69542c8d9fa703aebe2]"

task:
  name: KERNEL - Asus Zenfone Max Pro M1
  container:
    image: dopaemon/bionic
    cpu: 4
    memory: 8G

  clone_script:
    - mkdir -p ~/kernel
    - cd ~/kernel
    - git clone -b lineage-17.1 --single-branch --depth="1" https://github.com/LineageOS/android_kernel_asus_sdm660
    - git clone https://github.com/Doraemon-Kernel/arm-linux-androideabi-4.9.git /tmp/ci/gcc/arm
    - git clone https://github.com/Doraemon-Kernel/aarch64-linux-android-4.9.git /tmp/ci/gcc/arm64
    - git clone https://github.com/iAboothahir/KERNEL_BUILD-CI
    - cp -rv KERNEL_BUILD-CI/sdm660-overlay.dtsi ~/kernel/android_kernel_asus_sdm660/arch/arm/boot/dts/qcom/X00TD/sdm660-overlay.dtsi
  build_script:
    - cd ~/kernel/android_kernel_asus_sdm660
    - export ARCH=arm64
    - export CROSS_COMPILE=/tmp/ci/gcc/arm64/bin/aarch64-linux-android-
    - export CROSS_COMPILE_ARM32=/tmp/ci/gcc/arm/bin/arm-linux-androideabi-
    - make O=out X00TD_defconfig
    - make O=out -j$(nproc --all)
  flashable_script:
    - mkdir -p ~/kernel/flashable
    - cd ~/kernel/flashable
    - git clone -b master --depth="1" https://github.com/iAboothahir/AnyKernel3 zip
    - cp -r ~/kernel/android_kernel_asus_sdm660/out/arch/arm64/boot/Image.gz-dtb ~/kernel/flashable/zip/
    - cd zip
    - zip -rv9 "Lineage-17.1-kernel.zip" *
  telegram_script:
    - curl -F document=@"~/kernel/zip//K/Upload/Lineage-17.1-kernel.zip" https://api.telegram.org/bot$TLGTK/sendDocument?chat_id=-1001398988224
