env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    ALLOW_MISSING_DEPENDENCIES: "true"

    TLGTK: "ENCRYPTED[947923cb386537b5b64febb681804ae917eccc691323b69833f38c93107ee7b5be07e91449ddc69542c8d9fa703aebe2]"
    ZIPNAME: "/home/doraemon/kernel/flashable/zip/Halium-10-kernel.zip"

task:
  name: KERNEL - Asus Zenfone Max Pro M1
  container:
    image: dopaemon/bionic
    cpu: 4
    memory: 8G

  clone_script:
    - mkdir -p ~/kernel
    - cd ~/kernel
    - git clone -b halium-10 --single-branch --depth="1" https://github.com/Linux-On-Sdm6Series/kernel_asus_sdm660 android_kernel_asus_sdm660
    - git clone -b pie-gsi --depth="1" https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 /tmp/ci/gcc/arm
    - git clone -b pie-gsi --depth="1" https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 /tmp/ci/gcc/arm64
    - git clone -b android10-gsi --depth="1" https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 /tmp/ci/clang
    - git clone https://github.com/iAboothahir/KERNEL_BUILD-CI
    - # cp -rv KERNEL_BUILD-CI/sdm660-overlay.dtsi ~/kernel/android_kernel_asus_sdm660/arch/arm/boot/dts/qcom/X00TD/sdm660-overlay.dtsi
  build_script:
    - cd ~/kernel/android_kernel_asus_sdm660
    - export ARCH=arm64
    - export CROSS_COMPILE=/tmp/ci/gcc/arm64/bin/aarch64-linux-android-
    - export CROSS_COMPILE_ARM32=/tmp/ci/gcc/arm/bin/arm-linux-androideabi-
    - export PATH="/tmp/ci/clang/clang-r353983c/bin:${PATH}"
    - make O=out X00TD-perf_defconfig
    - make O=out -j$(nproc --all) CC=clang CLANG_TRIPLE=aarch64-linux-gnu-
  flashable_script:
    - mkdir -p ~/kernel/flashable
    - cd ~/kernel/flashable
    - git clone -b master --depth="1" https://github.com/iAboothahir/AnyKernel3 zip
    - cp -r ~/kernel/android_kernel_asus_sdm660/out/arch/arm64/boot/Image.gz-dtb ~/kernel/flashable/zip/
    - cd zip
    - zip -rv9 "Halium-10-kernel.zip" *
  telegram_script:
    - curl -F chat_id=-1001398988224 -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$TLGTK/sendDocument
