env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    ALLOW_MISSING_DEPENDENCIES: "true"

    TLGTK: "ENCRYPTED[947923cb386537b5b64febb681804ae917eccc691323b69833f38c93107ee7b5be07e91449ddc69542c8d9fa703aebe2]"
    ZIPNAME: "/home/doraemon/kernel/flashable/zip/Lineage-17.1-kernel.zip"

task:
  name: KERNEL - Asus Zenfone Max Pro M1
  container:
    image: dopaemon/bionic
    cpu: 4
    memory: 8G

  clone_script:
    - mkdir -p ~/kernel
    - cd ~/kernel
    - git clone -b lineage-17.1 --single-branch --depth="1" https://github.com/LineageOS/android_kernel_asus_sdm660
    - git clone -b master --single-branch --depth="1" https://github.com/radcolor/arm-linux-gnueabi.git /tmp/ci/gcc/arm
    - git clone -b master --single-branch --depth="1" https://github.com/radcolor/aarch64-linux-gnu.git /tmp/ci/gcc/arm64
    - git clone -b master --single-branch --depth="1" https://github.com/kdrag0n/proton-clang.git /tmp/ci/clang
    - git clone https://github.com/iAboothahir/KERNEL_BUILD-CI
    - # cp -rv KERNEL_BUILD-CI/sdm660-overlay.dtsi ~/kernel/android_kernel_asus_sdm660/arch/arm/boot/dts/qcom/X00TD/sdm660-overlay.dtsi
    - touch ~/.kernel
    - echo "export PATH="/tmp/ci/clang/bin:${PATH}"" >> ~/.kernel
    - echo "export CC=clang" >> ~/.kernel
    - echo "export ARCH=arm64" >> ~/.kernel
    - echo "export SUBARCH=arm64" >> ~/.kernel
    - echo "export CROSS_COMPILE=/tmp/ci/gcc/arm64/bin/aarch64-linux-gnu-" >> ~/.kernel
    - echo "export CROSS_COMPILE_ARM32=/tmp/ci/gcc/arm/bin/arm-linux-gnueabi-" >> ~/.kernel
    - echo "export PATH="/tmp/ci/clang/bin:${PATH}"" >> ~/.kernel
  build_script:
    - source ~/.kernel
    - cd ~/kernel/android_kernel_asus_sdm660
    - make O=out X00TD_defconfig
    # - make O=out -j$(nproc --all) ARCH=arm64 CC=clang CLANG_TRIPLE=/tmp/ci/clang/bin/aarch64-linux-gnu-
    - make -j$(nproc --all) O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=/tmp/ci/gcc/arm64/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=/tmp/ci/gcc/arm/bin/arm-linux-gnueabi-
  flashable_script:
    - mkdir -p ~/kernel/flashable
    - cd ~/kernel/flashable
    - git clone -b master --depth="1" https://github.com/iAboothahir/AnyKernel3 zip
    - cp -r ~/kernel/android_kernel_asus_sdm660/out/arch/arm64/boot/Image.gz-dtb ~/kernel/flashable/zip/
    - cd zip
    - zip -rv9 "Lineage-17.1-kernel.zip" *
  telegram_script:
    - curl -F chat_id=-1001398988224 -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$TLGTK/sendDocument
